import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const nirmala = localFont({
	src: "./Nirmala.ttf",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Salvation Ministries Lekki",
   description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				style={{
					overflowX: "hidden",
				}}
				className={nirmala.className}
			>
				<Navbar />
				<main className="overflow-hidden relative">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
