import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToasterProvider from "@/lib/ToastProvider";
import { Analytics } from "@vercel/analytics/react";

const nirmala = localFont({
	src: "./Nirmala.ttf",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Salvation Ministries Lekki",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modals,
}: Readonly<{
	children: React.ReactNode;
	modals: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				style={{
					overflowX: "hidden",
				}}
				className={nirmala.className}
         >
            <ToasterProvider />
				<Navbar />
				<main className="overflow-hidden relative">
					{modals}
               {children}
               <Analytics />
				</main>
				<Footer />
			</body>
		</html>
	);
}
